[package]
name = "kubesecrets"
description = "Tool to manage secrets in Kubernetes with kubectl"
version = "0.1.0"
authors = ["Chris Atkin <atkinchris@gmail.com>"]

[dependencies]
clap = "2.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
